# Generated by Django 3.1.5 on 2021-01-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_evaluator', '0002_auto_20210126_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
