# Generated by Django 3.1.5 on 2021-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0004_criteriongroup_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriongroup',
            name='abbr',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
