# Generated by Django 3.1.5 on 2021-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0005_criteriongroup_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
