# Generated by Django 3.1.5 on 2021-02-05 15:33

import application_evaluator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0008_applicationattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRoundAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('attachment',
                 models.FileField(max_length=256, upload_to=application_evaluator.models.upload_round_attachment_to)),
                ('application_round',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
                                   to='application_evaluator.applicationround')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
