# Generated by Django 3.1.5 on 2021-02-10 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0009_applicationroundattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
