# Generated by Django 3.1.5 on 2021-02-10 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_evaluator', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRoundSubmittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_round',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals',
                                   to='application_evaluator.applicationround')),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals',
                                   to='application_evaluator.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='applicationround',
            name='submitted_organizations',
            field=models.ManyToManyField(blank=True, related_name='submitted_application_rounds',
                                         through='application_evaluator.ApplicationRoundSubmittal',
                                         to='application_evaluator.Organization'),
        ),
    ]
