# Generated by Django 3.1.5 on 2021-02-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0012_auto_20210210_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
