# Generated by Django 3.1.5 on 2021-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0013_applicationround_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='Content that will be shown to the evaluators in the public UI. May use <a href="https://www.markdownguide.org/basic-syntax/">Markdown</a> for e.g. links and formatting.'),
        ),
    ]
