# Generated by Django 3.1.5 on 2021-06-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0014_applicationround_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['group_id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='criteriongroup',
            options={'ordering': ['application_round_id', 'order']},
        ),
        migrations.AlterField(
            model_name='applicationround',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='Content that will be shown to the evaluators in the public UI. May use <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown</a> for e.g. links and formatting.'),
        ),
    ]
