# Generated by Django 3.1.5 on 2022-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0015_auto_20210614_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='Content that will be shown to the evaluators in the public UI. May use <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown</a> for e.g. links and formatting.'),
        ),
    ]
