# Generated by Django 3.1.5 on 2023-03-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('application_evaluator', '0016_application_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=256, upload_to='application_imports')),
                ('error', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('processing', 'Processing'), ('error', 'Error'),
                             ('done', 'Done')], default='pending', max_length=16)),
                ('application_round',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_imports',
                                   to='application_evaluator.applicationround')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
