# Generated by Django 3.2.18 on 2023-03-30 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_evaluator', '0018_auto_20230316_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='evaluators',
            field=models.ManyToManyField(blank=True, related_name='evaluated_application_rounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='scoring_completed',
            field=models.BooleanField(default=False, help_text='Set by an admin to close scoring for this round.'),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='scoring_model',
            field=models.CharField(choices=[('Evaluators average', 'Evaluators average'), ('Organizations average', 'Organizations average')], default='Evaluators average', max_length=32),
        ),
    ]
