# Generated by Django 3.2.18 on 2023-04-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_evaluator', '0019_auto_20230330_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationimport',
            name='application_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationimports', to='application_evaluator.applicationround'),
        ),
        migrations.CreateModel(
            name='ApplicationAttachmentImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=256, upload_to='application_imports')),
                ('error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('error', 'Error'), ('done', 'Done')], default='pending', max_length=16)),
                ('application_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationattachmentimports', to='application_evaluator.applicationround')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
