# Generated by Django 3.2.18 on 2023-04-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_evaluator', '0020_auto_20230402_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='evaluating_organizations',
            field=models.ManyToManyField(blank=True, related_name='applications_to_evaluate', to='application_evaluator.Organization'),
        ),
        migrations.AlterField(
            model_name='applicationimport',
            name='application_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicationimports', to='application_evaluator.applicationround'),
        ),
    ]
