# Generated by Django 3.2.18 on 2023-04-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_evaluator', '0021_auto_20230404_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_application_rounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
