# Generated by Django 3.2.18 on 2023-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_evaluator', '0022_applicationround_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
