# Generated by Django 4.2.4 on 2023-11-01 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_evaluator', '0023_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='applicationattachment',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='applicationattachmentimport',
            name='application_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='application_evaluator.applicationround'),
        ),
        migrations.AlterField(
            model_name='applicationimport',
            name='application_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='application_evaluator.applicationround'),
        ),
        migrations.AlterField(
            model_name='applicationround',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='applicationroundattachment',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='application_evaluator.application'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='criteriongroup',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='score',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='application_evaluator.application'),
        ),
        migrations.AlterField(
            model_name='score',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
