# Generated by Django 4.2.4 on 2023-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_evaluator', '0024_applicationround_city_alter_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='other_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
