# Generated by Django 4.2.4 on 2024-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_evaluator', '0025_application_other_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
    ]
