version: '3.7'

services:
  web:
    build: ./django_server
    command: gunicorn application_evaluator_config.wsgi:application --bind 0.0.0.0:8001 --workers 4
    network_mode: host
    env_file:
      - ./.env.prod
    volumes:
      - ./django_server:/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"

  react:
    build: ./react_ui
    command: yarn build
    volumes:
      - ./react_ui:/app
      - /app/node_modules
